
newPRWelcomeComment: >
  Thanks so much for opening your first PR here!
firstPRMergeComment: >
  Congrats on merging your first pull request here! :tada: How awesome!
newIssueWelcomeComment: >
  Thanks for opening this issue, a maintainer will get back to you shortly!
sentimentBotToxicityThreshold: .7

sentimentBotReplyComment: >
  Please be sure to review the code of conduct and be respectful of other users. cc/ @YasiOnFire
lockThreads:
  toxicityThreshold: .7
  numComments: 2
  setTimeInHours: 72
  replyComment: >
    This thread is being locked due to exceeding the toxicity minimums. cc/ @YasiOnFire
