name: Code Review

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: deps, build, and test
        run: |
          yarn
          yarn run build
          yarn run test:unit
        env:
          CI: true
